version: "3.8"

# Services
services:
  # Nginx Service
  # http://localhost:8000 
  nginx:
    image: nginx:1.19
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/php
      - ./docker/nginx/conf.d:/etc/nginx/conf.d      
    depends_on:
      - php

  # PHP 
  php:
    build: ./docker/php
    working_dir: /var/www/php
    volumes:
      - ./:/var/www/php
    environment:
      DB_HOST: mysql
      DB_NAME: quiz
      DB_USER: Tobias
      DB_PASSWORD: mySql

    depends_on:
      mysql:
        condition: service_healthy

  # MySQL Service
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz
      MYSQL_USER: Tobias
      MYSQL_PASSWORD: mySql
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      retries: 10

  # PhpMyAdmin Service
  # http://localhost:8080 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy

# Volumes
volumes:
  db_data:
    driver: local
